# This is a basic workflow to help you get started with Actions

name: PUBLISH GITHUB ARTIFACT TUORIAL

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "archive-build-artifact"
  archive-build-artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: Step 2 - Add artifacts to publish to temporary folder
        run: |
          cd downloads
          echo  'alpha'    >  alpha.html
          echo  'bravo'    >  bravo.html
          echo  'charlie'  >  charlie.html
          cd ..
          
          
      - name: Step 3 - Use the Upload Artifact Github Action
        uses: actions/upload-artifact@v3.1.2
          with:
             # Artifact name
           name: asset-for-downloads
           # A file, directory or wildcard pattern that describes what to upload
           path: downloads
         

    
